package org.poolen.util;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * A utility class to load application properties (like name and version)
 * from a properties file generated by Maven.
 */
public final class AppConfig {

    private static final Properties properties = new Properties();
    private static final String APP_NAME;

    // A static initializer block to load the properties file once when the class is first used.
    static {
        try (InputStream input = AppConfig.class.getClassLoader().getResourceAsStream("application.properties")) {
            if (input == null) {
                System.err.println("ERROR: Could not find application.properties file in classpath.");
                // Set a sensible default name if the properties file is missing for any reason.
                APP_NAME = "MatchmakerApp";
            } else {
                properties.load(input);
                APP_NAME = properties.getProperty("app.name");
            }
        } catch (IOException ex) {
            System.err.println("ERROR: Failed to load application properties.");
            ex.printStackTrace();
            // In case of an error, throw an exception to make the problem obvious.
            throw new RuntimeException("Failed to load application properties", ex);
        }
    }

    /**
     * Private constructor to prevent instantiation.
     */
    private AppConfig() {
        // This is a utility class.
    }

    /**
     * Gets the application name from the loaded properties.
     * @return The application name as defined in the pom.xml.
     */
    public static String getAppName() {
        if (APP_NAME == null || APP_NAME.trim().isEmpty() || APP_NAME.startsWith("$")) {
            // This handles cases where the property is missing or Maven filtering didn't run
            return "MatchmakerApp";
        }
        return APP_NAME;
    }
}
